"""
validate_all_factors.py
Checks EVERY feature the model uses for internal consistency - does the
SHAP direction agree with what the real ground-truth data actually shows?

This produces a definitive list of which factors are reliable enough to
show in the dashboard, and which should be hidden because they behave
inconsistently or are too weak to trust for individual explanations.

Run:  python src/validate_all_factors.py
"""

import numpy as np
import pandas as pd
from db_loader import get_conn
from config import ALL_FEATS

shap_vals = np.load("results/shap_values.npy")
shap_feats = pd.read_csv("results/shap_input_features.csv")

conn = get_conn()
fm = pd.read_sql(f"SELECT wfd_status, {', '.join(ALL_FEATS)} FROM feat_matrix", conn)
conn.close()

MIN_CORRELATION = 0.15  # below this, treat as too weak/noisy to trust

results = []
for feat in ALL_FEATS:
    idx = shap_feats.columns.get_loc(feat)
    corr = np.corrcoef(shap_feats[feat].values, shap_vals[:, idx])[0, 1]

    # Using MEANS, not medians. Some features (like phosphate) are
    # right-skewed - most locations have similar low values, but Poor
    # locations include a meaningful tail of severely polluted outliers.
    # Medians miss this entirely (both classes can look identical), while
    # the mean correctly reflects it. Confirmed this mattered for
    # phosphate: median showed 0.035 vs 0.035 (identical), but mean
    # showed 0.124 vs 0.143 - a real difference the median hid.
    med_moderate = fm[fm["wfd_status"] == "Moderate"][feat].mean()
    med_poor = fm[fm["wfd_status"] == "Poor"][feat].mean()

    # SHAP positive = pushes toward Poor. If real data agrees, Poor's
    # mean should genuinely be higher than Moderate's, and vice versa.
    shap_says_poor_higher = corr > 0
    real_poor_higher = med_poor > med_moderate

    directions_agree = shap_says_poor_higher == real_poor_higher
    strong_enough = abs(corr) >= MIN_CORRELATION
    reliable = directions_agree and strong_enough

    results.append({
        "feature": feat,
        "shap_corr": round(corr, 3),
        "moderate_median": round(med_moderate, 2),
        "poor_median": round(med_poor, 2),
        "directions_agree": directions_agree,
        "strong_enough": strong_enough,
        "RELIABLE": reliable,
    })

df = pd.DataFrame(results).sort_values("shap_corr", key=abs, ascending=False)
pd.set_option("display.width", 140)
print(df.to_string(index=False))

reliable_feats = df[df["RELIABLE"]]["feature"].tolist()
unreliable_feats = df[~df["RELIABLE"]]["feature"].tolist()

print()
print("=" * 70)
print(f"RELIABLE ({len(reliable_feats)}) - safe to show in dashboard:")
for f in reliable_feats:
    print(f"  {f}")

print()
print(f"NOT RELIABLE ({len(unreliable_feats)}) - hide from dashboard explanations:")
for f in unreliable_feats:
    print(f"  {f}")

# Save the reliable list so the dashboard can import it directly
with open("results/reliable_features.py", "w") as f:
    f.write("# Auto-generated by validate_all_factors.py\n")
    f.write("# Only these features are shown in per-location explanations,\n")
    f.write("# since they're the ones where SHAP's direction genuinely\n")
    f.write("# agrees with real ground-truth medians, at a meaningful strength.\n")
    f.write(f"RELIABLE_FEATURES = {reliable_feats!r}\n")

# Also save the raw correlation per feature - needed for the
# per-location consistency check in the dashboard, which judges each
# factor individually at each location rather than using one fixed list.
corr_dict = dict(zip(df["feature"], df["shap_corr"]))
with open("results/feature_correlations.json", "w") as f:
    import json
    json.dump(corr_dict, f, indent=2)

print()
print("Saved to results/reliable_features.py")
print("Saved to results/feature_correlations.json")